# Generated by Django 4.1.2 on 2022-12-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_for_get_data', models.CharField(max_length=300)),
                ('login_for_that_site', models.CharField(max_length=50)),
                ('password_for_that_site', models.CharField(max_length=50)),
                ('link_for_upload_data2', models.CharField(max_length=300)),
                ('login_for_that_site2', models.CharField(max_length=300)),
                ('password_for_that_site2', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'UploadData',
                'db_table': 'UploadData',
            },
        ),
    ]
