# Generated by Django 4.1.2 on 2022-12-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploaddatas',
            options={'verbose_name_plural': 'uploadData'},
        ),
        migrations.AlterModelTable(
            name='uploaddatas',
            table='uploadData',
        ),
    ]
