# Generated by Django 4.1.2 on 2022-12-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_alter_uploaddatas_options_alter_uploaddatas_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploaddatas',
            options={'verbose_name_plural': 'upload_data'},
        ),
        migrations.AlterModelTable(
            name='uploaddatas',
            table='upload_data',
        ),
    ]
