# Generated by Django 4.1.2 on 2022-12-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_alter_uploaddatas_options_alter_uploaddatas_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddatas',
            name='link_for_get_data',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='uploaddatas',
            name='link_for_upload_data2',
            field=models.URLField(max_length=300),
        ),
    ]
