# Generated by Django 4.1.2 on 2022-12-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_uploaddatas_input_your_folder_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddatas',
            name='input_your_folder_path',
            field=models.CharField(default='path kiritilmagan', max_length=100),
        ),
    ]
