# Generated by Django 4.1.2 on 2022-12-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_alter_uploaddatas_input_your_folder_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddatas',
            name='password_for_that_site2',
            field=models.FilePathField(max_length=50),
        ),
    ]
