# Generated by Django 4.1.2 on 2022-12-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_alter_uploaddatas_password_for_that_site2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddatas',
            name='password_for_that_site2',
            field=models.CharField(max_length=50),
        ),
    ]
