# Generated by Django 4.1.2 on 2022-12-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_alter_uploaddatas_password_for_that_site2'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddatas',
            name='input_button_of_XPATH',
            field=models.CharField(default='xpath of button', max_length=400),
        ),
        migrations.AddField(
            model_name='uploaddatas',
            name='input_level_of_XPATH',
            field=models.CharField(default='xpath of level', max_length=400),
        ),
    ]
