# Generated by Django 4.1.2 on 2022-12-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_uploaddatas_input_button_of_xpath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddatas',
            name='input_level_of_XPATH',
            field=models.CharField(choices=[('level_1', '1'), ('level_1', '2'), ('level_1', '3')], default='leve', max_length=40),
        ),
        migrations.AlterField(
            model_name='uploaddatas',
            name='link_for_get_data',
            field=models.URLField(default='https://intranet.ytit.uz/login/index.php', max_length=300),
        ),
        migrations.AlterField(
            model_name='uploaddatas',
            name='link_for_upload_data2',
            field=models.URLField(default='https://lms.spprt.uz/#/auth/login', max_length=300),
        ),
        migrations.AlterField(
            model_name='uploaddatas',
            name='login_for_that_site',
            field=models.CharField(default='ier20037', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploaddatas',
            name='password_for_that_site',
            field=models.CharField(default='AC2558243', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploaddatas',
            name='password_for_that_site2',
            field=models.CharField(default='password', max_length=50),
        ),
    ]
