# Generated by Django 4.1.2 on 2022-12-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_alter_uploaddatas_input_level_of_xpath_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaddatas',
            old_name='input_button_of_XPATH',
            new_name='course_details_button_of_XPATH',
        ),
        migrations.AddField(
            model_name='uploaddatas',
            name='name_of_course',
            field=models.CharField(default='course nomi kiritilmagan', max_length=70),
        ),
        migrations.AlterField(
            model_name='uploaddatas',
            name='input_level_of_XPATH',
            field=models.CharField(choices=[('1asdasd', 'level_1'), ('2adsdsad', 'level_2'), ('3asdsad', 'level_3')], default='level_1', max_length=40),
        ),
    ]
