# Generated by Django 4.1.2 on 2022-12-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0011_rename_input_button_of_xpath_uploaddatas_course_details_button_of_xpath_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaddatas',
            name='course_details_button_of_XPATH',
        ),
    ]
