# Generated by Django 4.1.2 on 2022-12-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_remove_uploaddatas_course_details_button_of_xpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddatas',
            name='input_level_of_XPATH',
            field=models.CharField(choices=[('1 kurs', '/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div'), ('2 kurs', 'level_2'), ('3 kurs', 'level_3')], default='/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', max_length=40),
        ),
    ]
