# Generated by Django 4.1.2 on 2022-12-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0014_alter_uploaddatas_input_level_of_xpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddatas',
            name='link_for_get_data',
            field=models.URLField(default='https://intranet.ytit.uz/course/view.php?id=3577', max_length=300),
        ),
    ]
