# Generated by Django 4.1.2 on 2022-12-22 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0015_alter_uploaddatas_link_for_get_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mylevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_l1', models.CharField(default='berilmagan course XPATH', max_length=200)),
                ('level_l2', models.CharField(default='berilmagan course XPATH', max_length=200)),
                ('level_l3', models.CharField(default='berilmagan course XPATH', max_length=200)),
                ('level_l4', models.CharField(default='berilmagan course XPATH', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='uploaddatas',
            name='input_level_of_XPATH',
            field=models.ForeignKey(default='/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', on_delete=django.db.models.deletion.CASCADE, to='basic_app.mylevel'),
        ),
    ]
