# Generated by Django 4.1.2 on 2022-12-22 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0016_mylevel_alter_uploaddatas_input_level_of_xpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddatas',
            name='input_level_of_XPATH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.mylevel'),
        ),
    ]
