# Generated by Django 4.1.2 on 2022-12-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0017_alter_uploaddatas_input_level_of_xpath'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mylevel',
            options={'verbose_name_plural': 'mylevel'},
        ),
        migrations.AlterModelTable(
            name='mylevel',
            table='mylevel',
        ),
    ]
