# Generated by Django 4.1.2 on 2022-12-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0020_rename_level_1_mylevel_level_remove_mylevel_level_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaddatas',
            name='input_wait_time',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
