# Generated by Django 4.1.2 on 2022-12-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0022_rename_input_wait_time_uploaddatas_input_wait_time_when_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddatas',
            name='link_for_get_data',
            field=models.URLField(default='https://intranet.ytit.uz/course/view.php?id=3513', max_length=300),
        ),
        migrations.AlterField(
            model_name='uploaddatas',
            name='link_for_upload_data2',
            field=models.URLField(default='https://kiut.wisespace.uz/#/auth/login', max_length=300),
        ),
    ]
