# Generated by Django 4.1.2 on 2022-12-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0024_remove_uploaddatas_input_wait_time_when_upload_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaddatas',
            name='login_for_that_site',
        ),
        migrations.RemoveField(
            model_name='uploaddatas',
            name='password_for_that_site',
        ),
    ]
