# Generated by Django 4.1.2 on 2022-12-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0027_alter_student_year_in_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterField(
            model_name='uploaddatas',
            name='input_level_of_XPATH',
            field=models.CharField(choices=[('/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', 'level_1'), ('/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', 'level_2'), ('/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', 'level_3'), ('/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', 'level_4')], default='/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', max_length=100),
        ),
    ]
