# Generated by Django 4.1.2 on 2022-12-25 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0028_delete_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', 'level_1'), ('/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', 'level_2'), ('/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', 'level_3'), ('/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', 'level_4')], default='/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='uploaddatas',
            name='level',
            field=models.CharField(choices=[('/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', 'level_1'), ('/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', 'level_2'), ('/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', 'level_3'), ('/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', 'level_4')], default='/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', max_length=100),
        ),
        migrations.AlterField(
            model_name='uploaddatas',
            name='input_level_of_XPATH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.mylevel'),
        ),
    ]
