# Generated by Django 4.1.2 on 2022-12-26 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0032_alter_student_year_in_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', 'LEVEL_1'), ('asd', 'LEVEL_2'), ('Ss', 'LEVEL_3'), ('dsS', 'LEVEL_4')], default='/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', max_length=100),
        ),
        migrations.AlterField(
            model_name='uploaddatas',
            name='input_level_of_XPATH',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_app.student'),
        ),
    ]
