# Generated by Django 4.1.2 on 2022-12-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0033_alter_student_year_in_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', 'LEVEL_1'), ('asd', 'LEVEL_2'), ('Ss', 'LEVEL_3'), ('dsS', 'LEVEL_4')], max_length=100),
        ),
        migrations.AlterField(
            model_name='uploaddatas',
            name='input_level_of_XPATH',
            field=models.CharField(choices=[('/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', 'LEVEL_1'), ('asd', 'LEVEL_2'), ('Ss', 'LEVEL_3'), ('dsS', 'LEVEL_4')], max_length=100),
        ),
    ]
