# Generated by Django 4.1.2 on 2022-12-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0034_alter_student_year_in_school_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mylevel',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
