# Generated by Django 4.1.2 on 2022-12-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0036_alter_uploaddatas_input_level_of_xpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddatas',
            name='input_level_of_XPATH',
            field=models.CharField(choices=[('/html/body/div[1]/div[2]/div[2]/main/div[2]/div[1]/div', 'LEVEL_1'), ('/html/body/div[1]/div[2]/div[2]/main/div[2]/div[2]/div', 'LEVEL_2'), ('/html/body/div[1]/div[2]/div[2]/main/div[2]/div[3]/div', 'LEVEL_3'), ('/html/body/div[1]/div[2]/div[2]/main/div[2]/div[4]/div', 'LEVEL_4')], max_length=100),
        ),
    ]
