# Generated by Django 4.1.2 on 2022-12-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0037_alter_uploaddatas_input_level_of_xpath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaddatas',
            old_name='input_level_of_XPATH',
            new_name='input_level',
        ),
    ]
